### ISSUE TITLE
conversation article

### ISSUE THREAD

**Issue by dicook** [ropenscilabs/learningtower#1]
topics to cover:

- [ ] variability is larger than decline
- [ ] china is Shanghai and Macao and Hong Kong
- [ ] discuss package
- [ ] Individual students can be high scoring even in the poorest of locations

**Comment by dicook** [comment]
See existing Conversation article

https://theconversation.com/vital-signs-australias-slipping-student-scores-will-lead-to-greater-income-inequality-128301

and news articles include:

Australia
- https://www.abc.net.au/news/2019-12-03/australia-education-results-maths-reading-science-getting-worse/11760880
- https://www.abc.net.au/news/2019-12-07/the-demise-of-australian-mathematics-teachers-students/11768644
- https://www.theguardian.com/australia-news/2019/dec/03/australian-students-maths-performance-falls-to-oecd-average-in-worst-result-since-2000
- https://www.smh.com.au/education/alarm-bells-australian-students-record-worst-result-in-global-tests-20191203-p53gie.html
- https://www.dailytelegraph.com.au/subscribe/news/1/?sourceCode=DTWEB_WRE170_a_GGL&dest=https://www.dailytelegraph.com.au/education/early-years/australian-education-system-in-need-of-urgent-reform-after-shock-report/news-story/d349f13c09b50aaeda6f65ecbf1e5cc8&memtype=anonymous&mode=premium

New Zealand
- https://www.rnz.co.nz/news/national/404762/nz-teenagers-hit-new-lows-in-reading-maths-and-science-tests
- https://www.stuff.co.nz/national/education/117890945/new-zealand-topend-in-oecds-latest-pisa-report-but-drop-in-achievements-worrying
- https://www.stuff.co.nz/national/education/117924806/educations-leaning-tower-of-pisa

Indonesia
- https://www.thejakartapost.com/news/2019/12/04/not-even-mediocre-indonesian-students-score-low-in-math-reading-science-pisa-report.html

**Comment by gvdr** [comment]
Do you want to propose a timetable Di?
