### ISSUE TITLE
Split the student data in to unique years

### ISSUE THREAD

**Issue by priya51096** [ropenscilabs/learningtower#10]
In order to deal with the RMD checks and files sizes and submit the package on cran, we need to split the student rda data file into seven different years.

**Comment by kevinwang09** [comment]
@priya51096, as you won't be committing this script, so it will be good if you can share the R script with me and then I will put this in the masonry repo.

**Comment by priya51096** [comment]
the load_student function has now been created and this can also be seen at 7a6f9304444bc1850bd4f663c24dfaec27122db1. With this function, the user will be able to load all the data as well as the data for the desired year(s)

**Comment by priya51096** [comment]
The student data has been split into seven-year from 2000-2018. The following can be seen at 5a721b5925c95b608accfc52afb888611b0f8cca
