### ISSUE TITLE
Write smaller vignettes for the package

### ISSUE THREAD

**Issue by kevinwang09** [ropenscilabs/learningtower#12]
These vignettes should be placed in the `vignettes` folder with any relevant packages declared in https://github.com/kevinwang09/learningtower/blob/5c82623bd358e0a6b39f379103dedc2fa3078667/DESCRIPTION#L35.

**Comment by priya51096** [comment]
The vignettes for the package have been written. This can be seen at 3790066fb2a19904e8768eb71602802b75eb57e8 and 0895cee531249f3237868aaf3f7ddb2e1ade84db
