### ISSUE TITLE
Write `load_student()` function

### ISSUE THREAD

**Issue by kevinwang09** [ropenscilabs/learningtower#13]
This should be done after #10, and this function should have the flexibility of loading all the data at once or load them separately. 
Also need examples to go along.

**Comment by priya51096** [comment]
The load_student function has been created, This function allows the user to download the student data for the desired year(s) as well the entire can be downloaded using the "all" as a param to the function.  The same can be seen here - 7a6f9304444bc1850bd4f663c24dfaec27122db1. Note - the data has now been replaced by rds format
