### ISSUE TITLE
Create a folder student_full_data

### ISSUE THREAD

**Issue by priya51096** [ropenscilabs/learningtower#14]
Add the student data for each year from 2000-2018.

**Comment by kevinwang09** [comment]
Initialised in 10c4f74bc4c6fd151d8d553703759f4c71c6264a, completed using `rds` files in 7a6f9304444bc1850bd4f663c24dfaec27122db1

**Comment by priya51096** [comment]
The entire student data has been placed the student_full_data folder. Seen at 10c4f74bc4c6fd151d8d553703759f4c71c6264a.
