### ISSUE TITLE
Function(s) to download the the student data from GitHub

### ISSUE THREAD

**Issue by priya51096** [ropenscilabs/learningtower#15]
Write a function in the package that allows the user to download the student data for the desired year from 2000-2018, directly from Github

**Comment by kevinwang09** [comment]
Extension of #13

**Comment by priya51096** [comment]
The load_student function allows the user to download the data from GitHub from the student_full_data folder. This issue is an extension of the issue - https://github.com/kevinwang09/learningtower/issues/13. This has been cleared and can be seen at 7a6f9304444bc1850bd4f663c24dfaec27122db1
