### ISSUE TITLE
unable to use load_student

### ISSUE THREAD

**Issue by lucasph97** [ropenscilabs/learningtower#29]
Hi Kevin, hope you are well 
First of all many thanks for providing this dataset and for maintaining it
I am having issues loading student data. The function `load_student` isn't working
For instance I ran `load_student(2018)` and got that
```
Warning: cannot open URL 'https://github.com/kevinwang09/learningtower/raw/master/student_full_data/student_2018.rds': HTTP status was '404 Not Found'Error in utils::download.file(url = url_git, destfile = tmp) : 
  cannot open URL 'https://github.com/kevinwang09/learningtower/raw/master/student_full_data/student_2018.rds'
```
It was working yesterday tho. Perhaps something went wrong with the last changes? 
Hope you can make it. Thanks in advance

**Comment by kevinwang09** [comment]
Hi @lucasph97, thanks for letting us know, I have fixed the links now. It was because of a change in #28 that I didn't foresee to have changes at the user end. Apologies!

**Comment by lucasph97** [comment]
Hi there, many thanks for the quick reply and solution. It's indeed working correctly now! Much appreciated 👍
