### ISSUE TITLE
country code docs

### ISSUE THREAD

**Issue by kimnewzealand** [ropenscilabs/learningtower#5]
I have added some links to the country code documentation in the latest commit.

Please could someone review and confirm this is enough?

**Comment by kevinwang09** [comment]
Awesome @kimnewzealand! 
I did a re-clean of the data in the masonry repo a few days ago and I `left_join` country names from the `countrycode` package, and it looks like your curated set is much better. So if you don't mind, I want to move this `countrycode.rda` to the masonry repo first, add on the two extra rows of `ROM` and `YUG` (which are likely Romania and Yogoslavia, https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Transitional_reservations) and then export it back to the `learningtower` package. 

BTW: do you have scripts on how did you curate this `countrycode.rda`? We can also put this in the masonry repo for completeness. 

``` r
library(tidyverse)
library(learningtower)
student_country = student %>% dplyr::select(country, country_name) %>% distinct()
student_country %>% glimpse
#> Rows: 100
#> Columns: 2
#> $ country      <fct> ALB, ARG, AUS, AUT, BEL, BGR, BRA, CAN, CHE, CHL, CZE, D…
#> $ country_name <fct> Albania, Argentina, Australia, Austria, Belgium, Bulgari…
data("countrycode", package = "learningtower")
countrycode %>% glimpse
#> Rows: 98
#> Columns: 2
#> $ country_iso3c <chr> "AZE", "ARG", "AUS", "AUT", "BEL", "BRA", "BGR", "CAN",…
#> $ country_name  <chr> "Azerbaijan", "Argentina", "Australia", "Austria", "Bel…
###########################
## Checking the differences between the countrycode Kim curated and those from the countrycode package
full_country = full_join(student_country, countrycode, 
                         by = c("country" = "country_iso3c"), suffix = c("_package", "_kim"))
#> Warning: Column `country`/`country_iso3c` joining factor and character vector,
#> coercing into character vector

full_country %>% filter(is.na(country_name_package)) %>% glimpse
#> Rows: 19
#> Columns: 3
#> $ country              <chr> "ROM", "YUG", "TAP", "QCN", "QHP", "QTN", "QVE",…
#> $ country_name_package <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
#> $ country_name_kim     <chr> NA, NA, "Chinese Taipei", "Shanghai-China", "Him…
full_country %>% filter(is.na(country_name_kim)) %>% glimpse
#> Rows: 2
#> Columns: 3
#> $ country              <chr> "ROM", "YUG"
#> $ country_name_package <fct> NA, NA
#> $ country_name_kim     <chr> NA, NA
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kimnewzealand** [comment]
Great work @kevinwang09 .
I only added reference links in that [last commit](https://github.com/ropenscilabs/learningtower/commit/aa40fdce24ab00766f7c379698f218bd07938e5c) .

Who put countrycode.rda together at the unconf?

**Comment by kevinwang09** [comment]
Ah, I should've checked the git history, I think it was @dicook who first placed it in the repo. 
Just to be clear, in the `student.rda` data as of 09a1551, there is only a 3-letter code for the country. Whereas in `countrycode.rda`, the data has both the 3-letter code (100 rows now, when we include ROM and YUG) and the full name of the country.
