### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/learningtower#6]
@kimnewzealand @dicook et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by kevinwang09** [comment]
Hi @dicook, I remember you had some teaching/supervision plans with this package last time I had a casual chat with Emi? If there is still some plans to keep this project going, I am happy to contribute. 

In addition, I would also like to put my hand up to get the repo transferred to my personal account as I have done some additional curation last year and a little bit more up to date with the inner details of the package as it stands now.

**Comment by dicook** [comment]
Hi @kevinwang it would be lovely if you took it over! Emi and I were thinking of having someone over last summer break work on it but we didn’t get organised. We had two other students work on other projects and thinking about this one was a bit late. Maybe could be organised for next summer or later this year.

**Comment by dicook** [comment]
Hi Maelle,

@kevinwang would be keen to move this to his repo

> On 5 Apr 2021, at 10:46 pm, Maëlle Salmon ***@***.***> wrote:
> 
> 
> @kimnewzealand @dicook et al 👋 according to our recently created package curation policy this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.
> 
> If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.
> 
> Thank you!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by maelle** [comment]
Thanks both! Transfer to @kevinwang09 requested (not @kevinwang).

**Comment by kevinwang09** [comment]
Thanks a lot @dicook @maelle!

**Comment by maelle** [comment]
can you please accept the transfer? the repo is still in transit under my account

**Comment by maelle** [comment]
@kevinwang09 can you please accept the transfer before it expires? Thank you.

**Comment by kevinwang09** [comment]
Hi @maelle, I didn't see any notification for it, is it possible for you to resend it?

**Comment by maelle** [comment]
I've just aborted and re-requested the transfer. Usually one gets such notifications by email I think.

**Comment by maelle** [comment]
Hurray I see it worked!
