### ISSUE TITLE
Replace the vignettes to articles

### ISSUE THREAD

**Issue by priya51096** [ropenscilabs/learningtower#8]
We need to replace the existing vignettes files and rename them to articles and write short and smaller vignettes and include the current vignettes to the pkgdown website @kevinwang09

**Comment by kevinwang09** [comment]
https://github.com/kevinwang09/learningtower/commit/d76c641b3592a636218b15b43197d2d822be1b87 and https://github.com/kevinwang09/learningtower/commit/5c82623bd358e0a6b39f379103dedc2fa3078667 achieved the following: 
+ moving some vignettes from `vignettes` folder to the `inst` folder. 
+ moving the Australian vignette from `vignettes` folder to the `vignettes/articles` folder. 
+ Successful R CMD build in a reasonable time (https://github.com/kevinwang09/learningtower/actions/runs/1070970859)
+ Successful `pkgdown` build of the Australian vignette but not as a part of the R CMD (https://github.com/kevinwang09/learningtower/actions/runs/1070970861)

**Comment by kevinwang09** [comment]
@priya51096, I will leave it to you to write smaller vignettes. 

The rule of thumb from now on is that: 
1. If a vignette needs to go with a package, then any dependencies should be declared here: https://github.com/kevinwang09/learningtower/blob/5c82623bd358e0a6b39f379103dedc2fa3078667/DESCRIPTION#L35
2.If a vignette only needs to go on the website, then any dependencies should be declared here: https://github.com/kevinwang09/learningtower/blob/5c82623bd358e0a6b39f379103dedc2fa3078667/.github/workflows/pkgdown.yaml#L53

I tend to think the vignettes that are already written (sitting in `inst` folder) should just be copied into `vignettes/articles` and thus kept online only. 
You should aim to take selected chunks from the existing vignettes and convert them into either smaller vignettes or small examples like these: 
https://github.com/kevinwang09/learningtower/blob/5c82623bd358e0a6b39f379103dedc2fa3078667/R/data.R#L49
